### ISSUE TITLE
Hook v with diaeresis

### ISSUE THREAD

**Issue by iandoug** [HughP/dnj-corpus#28]
Hi

Are there any plans to get diaeresis versions of U+01B2 LATIN CAPITAL LETTER V WITH HOOK and U+028B LATIN SMALL LETTER V WITH HOOK into Unicode?

At this point I'm not entirely sure how to make it work on a single key on a keyboard, given that it also requires the combining diaeresis. Having it as one character will solve the problem.

Not sure where they will put them though as upper is in Latin Extended B and lower is in IPA extensions. Then we have to wait for font support ...

**Comment by HughP** [comment]
Unicode will not be adding any more Latin precomposed characters. The only reason the current ones exist was to match pre-existing code pages. 
The way to fool KLA on this issue is to change the character for computational processing. if the deadkey is ":" and the normal key is "u" then switch all instances of f U+01B2 to the sequences of ":u" but this presents a commitment to the deadky method before processing.

**Comment by iandoug** [comment]
AFAIK KLA has no concept of dead keys (or even Linux "compose" keys). All it knows is to match the glyph/character assigned to one of four slots on a key, to the character in the input text.
I'm trying to avoid having to use dead key method for input ... it's okay when you have to write naïve or coöperation once in a while but not for something as common as v-hook-diaresis in Dan. Case in point: last word in Chapter 6 of Mark: "klʋ̈ʋ̈klʋ̈ (which I stumbled across this afternoon).

I have asked on Shenafu.com for ideas as to how to make keyboard send two unicode code points with one keypress. It should be possible in theory. Have had no answer yet so make have to ask on GeekHack.
From my point of view, the keyboard should send a scancode (row 4, column 5 key pressed) and the keyboard driver should know that that means v-hook-diaeresis (because: user is using DNJ keyboard) but I don't know if the connection between keyboard driver and rest of OS/programs allows such things... I can't see why not.
At the moment on the layouts I'm testing I'm using upsilon-diaeresis with the intention of switching to v-hook-diaeresis when the technical issues are sorted.

However some keyboard drivers want to fake things the other way around, and pretend to be a plain US ANSI 104 to the OS. This means no software changes on computer, but don't think it was designed for this sort of use case.

**Comment by HughP** [comment]
The solution I came up with was for the analysis, to convert each part of the complex character to its own character and match it to the position on the keyboard under the QWERTY setting and then run the setting as QWERTY. This is because most analyzers don't have an appropriate level of abstraction.
