### ISSUE TITLE
Odd lines in final corpus

### ISSUE THREAD

**Issue by iandoug** [HughP/dnj-corpus#37]
Hi

Am finished playing with fonts for now so can come back to this... had a quick look at your final corpus and see lines of the form

    ˗Wo ʼdho ˗kɔ ( ) + + + saa + + gɛanˮ 

Is that how you want it?
Looks like a regex took too much out?

**Comment by HughP** [comment]
Yes there are some quirky residue issues. Here is how those got there. I have a portion of the script which removes all the french words. Those plus signs are between french words but are not just french, so I leave them. diff inital starting corpus and final corpus.  For now I am happy leaving them in, otherwise it is likely that we will remove the characters in their entirety from the corpus for a lack of mathematical content.
